// Copyright (C) 2020 Maxim, 2dev2fun@gmail.com. All rights reserved.

#pragma once

#include "Math.h"
#include "Math/Entity/Matrix2x2.h"
#include "Math/Entity/Matrix2x2/Function.h"
#include "Math/Entity/Matrix2x2/Hash.h"
#include "Math/Entity/Matrix2x2/Operator.h"
#include "Math/Entity/Matrix3x3.h"
#include "Math/Entity/Matrix3x3/Function.h"
#include "Math/Entity/Matrix3x3/Hash.h"
#include "Math/Entity/Matrix3x3/Operator.h"
#include "Math/Entity/Matrix4x4.h"
#include "Math/Entity/Matrix4x4/Function.h"
#include "Math/Entity/Matrix4x4/Hash.h"
#include "Math/Entity/Matrix4x4/Operator.h"
#include "Math/Entity/Quaternion.h"
#include "Math/Entity/Quaternion/Function.h"
#include "Math/Entity/Quaternion/Hash.h"
#include "Math/Entity/Quaternion/Operator.h"
#include "Math/Entity/Vector2.h"
#include "Math/Entity/Vector2/Function.h"
#include "Math/Entity/Vector2/Hash.h"
#include "Math/Entity/Vector2/Operator.h"
#include "Math/Entity/Vector3.h"
#include "Math/Entity/Vector4.h"
#include "Math/Entity/Vector4/Function.h"
#include "Math/Entity/Vector4/Hash.h"
#include "Math/Entity/Vector4/Operator.h"
#include "Math/System/Render.h"
